In [69]:
import math
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from matplotlib import pyplot as plt
from sklearn.metrics import confusion_matrix


In [2]:
train_in = np.loadtxt('../Datasets/train_in.csv', 
                  delimiter=',',   # 用于分割各列值的字符
                  skiprows=0,      # 跳过前两行
                #   usecols=[0, 2],  # 读取并使用第1列和第3列
                  dtype=float)       # 使用的数据类型
test_in = np.loadtxt('../Datasets/test_in.csv', 
                  delimiter=',',   # 用于分割各列值的字符
                  skiprows=0,      # 跳过前两行
                #   usecols=[0, 2],  # 读取并使用第1列和第3列
                  dtype=float)       # 使用的数据类型
train_out = np.loadtxt('../Datasets/train_out.csv', 
                  delimiter=',',   # 用于分割各列值的字符
                  skiprows=0,      # 跳过前两行
                #   usecols=[0, 2],  # 读取并使用第1列和第3列
                  dtype=float)       # 使用的数据类型
test_out = np.loadtxt('../Datasets/test_out.csv', 
                  delimiter=',',   # 用于分割各列值的字符
                  skiprows=0,      # 跳过前两行
                #   usecols=[0, 2],  # 读取并使用第1列和第3列
                  dtype=float)       # 使用的数据类型
# print(data)
# train_in = np.array(train_in)

In [3]:
X_train, X_test, y_train, y_test = train_test_split(train_in, train_out, train_size=0.8, random_state=0)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(1365, 256) (342, 256) (1365,) (342,)


In [92]:
# sigmoid function 
def sig(x):
    return (1/(1+np.exp(-x)))

def deridig(y):
    return y*(1-y)

Len_train = len(X_train)
Len_test = len(X_test)

# input dataset
def preprocessing(datasets):
    return np.hstack((datasets, np.ones(len(datasets)).reshape(len(datasets),1)))

train_x = preprocessing(X_train)
test_x = preprocessing(X_test)
test_in_x = preprocessing(test_in)

# weight
w0 = np.random.random((257,10))

# output dataset
y = np.zeros(Len_train * 10).reshape(Len_train,10)

#
np.random.seed(2022)

In [79]:
print(train_x.shape, w0.shape, y.shape, test_x.shape)

(1365, 257) (257, 10) (1365, 10) (342, 257)


In [25]:
def get_dummies(list, array):
    for i, each in zip(list, array):
        each[int(i)] = 1
    return array

In [26]:
y_train_dummy = np.zeros(Len_train*10).reshape(Len_train, 10)
y_train_dummy = get_dummies(y_train, y_train_dummy)
print(train_x.shape, w0.shape, y.shape)
print(y_train_dummy)

(1365, 257) (257, 10) (1365, 10)
[[0. 0. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]


In [95]:
def train(lr, w0, train_x, y_train_dummy):
    for iter in range(100000):
        y = sig(np.dot(train_x, w0))
        # e = pow((y_train_dummy - y) * (y_train_dummy - y), 0.5)
        e = y_train_dummy - y
        if iter % 100 == 0 :
           print(sum(sum(abs(e))))
        if sum(sum(abs(e))) <= 1e-04:
            print(iter)
            break
        # updata w0(weight)
        # print(w0.shape, train_x.shape, e.shape)
        # print((1-w0) * w0)
        # w0 += lr * np.dot(train_x.T, e) * ((1-w0) * w0)
        w0 += lr * np.dot(train_x.T, e)
        # print(sum(sum(((1-w0) * w0))))
    return w0

In [96]:
# y = np.zeros(Len_train * 10).reshape(Len_train,10)
w0 = np.random.random((257,10))
lr = 0.3
# b0 = 0.4
# e = 100
w = train(lr, w0, train_x, y_train_dummy)

1508.9154619730052


/var/folders/z4/snjl44yd2sz6dxh5_3nlrgyh0000gn/T/ipykernel_19072/2520368122.py:3: RuntimeWarning: overflow encountered in exp
  return (1/(1+np.exp(-x)))


129.37026030398633
118.49980378731483
9.60510229192409
2.000515190385721
0.0006591075373141126
0.000451810683677944
0.0003514542239921477
0.00028960795995736457
0.00024706914164889995
0.0002158216685767469
0.00019181839567856585
0.00017276562506490111
0.00015725629652265548
0.00014437543696753504
0.00013350065240970134
0.0001241930436397267
0.00011613382399215132
0.00010908564690687829
0.00010286803974116387
1951


In [97]:
### confusion Train
confusion_matrix(np.argmax(sig(np.dot(train_x, w)), axis=1),y_train)

/var/folders/z4/snjl44yd2sz6dxh5_3nlrgyh0000gn/T/ipykernel_19072/2520368122.py:3: RuntimeWarning: overflow encountered in exp
  return (1/(1+np.exp(-x)))


array([[248,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0, 203,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0, 159,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0, 109,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,  97,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,  66,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0, 121,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0, 136,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0, 118,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0, 108]])

In [98]:
### confusion test
confusion_matrix(np.argmax(sig(np.dot(test_in_

x, w)), axis=1),test_out)

/var/folders/z4/snjl44yd2sz6dxh5_3nlrgyh0000gn/T/ipykernel_19072/2520368122.py:3: RuntimeWarning: overflow encountered in exp
  return (1/(1+np.exp(-x)))


array([[215,   1,   6,   3,   3,   5,   5,   0,   7,   1],
       [  0, 116,   1,   0,   1,   0,   0,   0,   0,   1],
       [  4,   2,  88,   3,   5,   0,   7,   7,   3,   1],
       [  0,   0,   1,  65,   3,   6,   0,   2,   4,   1],
       [  3,   1,   0,   0,  65,   2,   2,   3,   1,   2],
       [  0,   0,   0,   2,   2,  40,   4,   0,   7,   0],
       [  0,   0,   1,   0,   1,   0,  72,   0,   0,   0],
       [  0,   1,   1,   1,   4,   1,   0,  50,   2,   4],
       [  1,   0,   3,   4,   0,   0,   0,   0,  68,   2],
       [  1,   0,   0,   1,   2,   1,   0,   2,   0,  76]])

### Task 1.3

In [99]:
# Preliminaries
import math
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier as knn
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_validate

In [100]:
def sig(x):
    return (1/(1+np.exp(-x)))

def sig_prime(x):
    return (x * (1 - x))


In [ ]:
input_list = []
hidden_list = []

def xor_net(inputs, weights):
    while(mse(w) != 0:)
        # predict process
        for i in len(input_list):
            for w in weights[0][i]:
                hidden_list[i] += w * input_list[i]
        for i in len(hidden_list):
            for w in weights[1][i]:
                output += w * hidden_list[i]
        p_error = error_prime(hidden_output, y)  # as error function

        # update process
        for i in len(weights[1]): # update hidden_weights
            weights[1][i] += p_error * hidden_list[i]
        for i in len(hidden_list): # update hidden
            hidden_list[i] = sig_prime(hidden_list[i]) * p_error * weights[1][i]
        for i in len(weights[0]): # update input_weights
            weights[0][i] += p_error * hidden_list[i]




In [153]:
weights = np.array(range(0,9,1)).reshape(3,3)
hidden_nodes = np.array([0,1,2])
d_hidden_nodes = np.array([0,1,2])
input_nodes = np.array([0,1,2])
y = np.array([4,5,6])
temp_weights_in =  np.array([0,1,2]).reshape(3,1)


while(mse() != 0):
    # predict process
    hidden_nodes = sum(input_nodes*temp_weights_in)
    output = hidden_nodes.dot(weights[1].T)

    error = y - output
    p_error = sig_prime(error)

    # update process
    d_hidden_nodes = sig_prime(hidden_nodes) * p_error * weights[1]
    weights[1] += hidden_nodes * p_error
    weights[0] += d_hidden_nodes * p_error


In [ ]:
def gradient_decent(weights, nodes):
    d_nodes = sig_prime(nodes[1]) * p_error * weights[1]
    weights[1] = lr * nodes[1] * p_error
    weights[0] = lr * d_nodes * p_error * nodes[0]
    return weights